spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/batches
    username: postgres
    password: postgres
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: false
        generate_statistics: true
